# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=300)),
                ('author_inst', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='utilty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('asso_author', models.TextField(default='null')),
                ('arxiv', models.CharField(default='null', max_length=100)),
                ('jour_name', models.CharField(max_length=250)),
                ('volume', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=50)),
                ('noofpages', models.IntegerField(default=0)),
            ],
        ),
    ]
