# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='utilty',
            new_name='utility',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
