# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.IntegerField(default='null')),
                ('ques', models.CharField(max_length=250)),
                ('choicecheck', models.CharField(choices=[('1', 'radio'), ('2', 'checkbox')], default='null', max_length=10)),
                ('noofoptions', models.DecimalField(decimal_places=5, default=0, max_digits=5, max_length=20)),
                ('anschoice', models.ManyToManyField(blank='true', default='null', related_name='_question_anschoice_+', to='dev_app.Question')),
            ],
        ),
    ]
