# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0002_auto_20171226_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='noofoptions',
            field=models.IntegerField(default=0),
        ),
    ]
