# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0007_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_attached', models.CharField(default='null', max_length=200)),
                ('grp_at_id', models.CharField(max_length=150)),
                ('grp_at_mail', models.TextField(default='null')),
                ('grp_mail', models.TextField(default='null')),
            ],
        ),
    ]
