# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0008_mail_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_msg_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_header', models.CharField(default='null', max_length=300)),
                ('msg_body', models.TextField(default='null')),
            ],
        ),
    ]
