# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0010_auto_20180105_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_send',
            name='user_token',
            field=models.TextField(default='null'),
        ),
    ]
