# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0012_answer_log_mail_sent_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_log',
            name='answerat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mail_sent_log',
            name='mailsentat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
