# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0015_auto_20180110_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='time_from',
            field=models.TimeField(default='null'),
        ),
        migrations.AddField(
            model_name='conference',
            name='time_to',
            field=models.TimeField(default='null'),
        ),
    ]
