# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0021_auto_20180112_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
