# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0023_auto_20180112_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_log',
            name='answerat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mail_sent_log',
            name='mailsentat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
