# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0025_auto_20180112_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_msg_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_header', models.CharField(default='null', max_length=300)),
                ('msg_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mail_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_at_mail', models.TextField()),
                ('grp_attached', models.CharField(default='null', max_length=200)),
                ('question_id', models.CharField(max_length=150)),
                ('grp_mail', models.TextField()),
                ('user_token', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='answer_log',
            name='answerkey',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='grp_email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mail_sent_log',
            name='usr_mail_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='anschoice',
            field=models.TextField(),
        ),
    ]
