# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0027_auto_20180115_0533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answer_log',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='mail_msg_titles',
        ),
        migrations.DeleteModel(
            name='Mail_send',
        ),
        migrations.DeleteModel(
            name='mail_sent_log',
        ),
    ]
