# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mail_sent_log', models.CharField(default='null', max_length=100, unique=True)),
                ('questionid', models.CharField(default='null', max_length=100)),
                ('answerkey', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=500)),
                ('note', models.TextField(max_length=500)),
                ('note2', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(max_length=250)),
                ('grp_email', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='mail_msg_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_header', models.CharField(default='null', max_length=300)),
                ('msg_body', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Mail_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_at_mail', models.TextField(default='null')),
                ('grp_attached', models.CharField(default='null', max_length=200)),
                ('question_id', models.CharField(max_length=150)),
                ('grp_mail', models.TextField(default='null')),
                ('user_token', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='mail_sent_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(default='null', max_length=300)),
                ('telid', models.CharField(default='null', max_length=100)),
                ('questionid', models.CharField(default='null', max_length=100)),
                ('usr_mail_token', models.TextField(default='null')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='anschoice',
        ),
        migrations.AddField(
            model_name='question',
            name='anschoice',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='question',
            name='noofoptions',
            field=models.IntegerField(default=0),
        ),
    ]
