# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0003_auto_20171226_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='anschoice',
        ),
        migrations.AddField(
            model_name='question',
            name='anschoice',
            field=models.TextField(default='null'),
        ),
    ]
