# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0003_auto_20180115_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
