# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0004_auto_20180115_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='noofoptions',
        ),
    ]
