# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0006_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=500)),
                ('note', models.TextField(max_length=500)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
    ]
