# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0014_auto_20180110_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_log',
            name='id_mail_sent_log',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
    ]
