# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0016_auto_20180112_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='time_from',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='time_to',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
