# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0017_auto_20180112_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
