# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0020_auto_20180112_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='time_to',
        ),
    ]
