# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0024_auto_20180112_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mail_msg_titles',
        ),
        migrations.DeleteModel(
            name='Mail_send',
        ),
    ]
