# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0026_auto_20180112_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_log',
            name='answerat',
        ),
        migrations.RemoveField(
            model_name='mail_sent_log',
            name='mailsentat',
        ),
    ]
