# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dev_app', '0029_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_mail_sent_log', models.CharField(default='null', max_length=100, unique=True)),
                ('questionid', models.CharField(default='null', max_length=100)),
                ('answerkey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(max_length=250)),
                ('grp_email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mail_msg_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_header', models.CharField(default='null', max_length=300)),
                ('msg_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mail_send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_at_mail', models.TextField()),
                ('grp_attached', models.CharField(default='null', max_length=200)),
                ('question_id', models.CharField(max_length=150)),
                ('grp_mail', models.TextField()),
                ('user_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mail_sent_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(default='null', max_length=300)),
                ('telid', models.CharField(default='null', max_length=100)),
                ('questionid', models.CharField(default='null', max_length=100)),
                ('usr_mail_token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=250)),
                ('choicecheck', models.CharField(choices=[('1', 'radio'), ('2', 'checkbox')], default='null', max_length=10)),
                ('noofoptions', models.IntegerField(default=0)),
                ('anschoice', models.TextField()),
            ],
        ),
    ]
