# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0030_answer_log_group_mail_msg_titles_mail_send_mail_sent_log_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_log',
            name='answerat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mail_sent_log',
            name='mailsentat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer_log',
            name='answerkey',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='group',
            name='grp_email',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='mail_msg_titles',
            name='msg_body',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='mail_send',
            name='grp_at_mail',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='mail_send',
            name='grp_mail',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='mail_send',
            name='user_token',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='mail_sent_log',
            name='usr_mail_token',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='question',
            name='anschoice',
            field=models.TextField(default='null'),
        ),
    ]
