# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0031_auto_20180115_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=500)),
                ('note', models.TextField(max_length=500)),
                ('note2', models.TextField(max_length=500)),
                ('date_from', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('date_to', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
