# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_app', '0033_auto_20180115_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_log',
            name='answerat',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='time_to',
        ),
        migrations.RemoveField(
            model_name='mail_sent_log',
            name='mailsentat',
        ),
    ]
